export const TrashData = [
    {
        Number: 1,
        Building: "CIT Building",
        Description: "Mountain Dew",
        WasteType: "Biodegradable",
        Weight: "30kg",
    },
    {
        Number: 2,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 3,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 4,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 5,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 6,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 7,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 8,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 9,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 10,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 11,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 12,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 13,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 14,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 15,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 16,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 17,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 18,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 19,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 20,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    },
    {
        Number: 21,
        Building: "CICS Building",
        Description: "Coca Cola",
        WasteType: "Biodegradable",
        Weight: "34kg",
    }
]